version: 2
updates:
  - package-ecosystem: cargo
    directory: ./crates
    schedule:
      interval: daily
    groups:
      all-rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: ./packages/cellnoor-auth
    schedule:
      interval: daily
    groups:
      all-auth-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: ./packages/cellnoor-ui
    schedule:
      interval: daily
    groups:
      all-ui-dependencies:
        patterns:
          - "*"
