version: 2
updates:
  - package-ecosystem: cargo
    directory: ./crates
    schedule:
      interval: daily
    groups:
      all-rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bun
    schedule:
      interval: daily
    directories:
      - ./packages/cellnoor-auth
      - ./packages/cellnoor-ui
