version: 2
updates:
  - package-ecosystem: cargo
    directory: .
    schedule:
      interval: daily
    groups:
      all-rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: .
    schedule:
      interval: daily
    groups:
      all-typescript-dependencies:
        patterns:
          - "*"
