services:
  cellnoor-auth:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-auth:latest
    pull_policy: always
    environment:
      NODE_ENV: &node_env production
  cellnoor-api:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-api:latest
    pull_policy: always
    environment:
      CELLNOOR_API__MAX_DB_POOL_SIZE: "4"
  cellnoor-ui:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-ui:latest
    pull_policy: always
    environment:
      NODE_ENV: *node_env
  caddy:
    environment:
      CELLNOOR_PUBLIC_BASE_URL: ${CELLNOOR_PUBLIC_BASE_URL}
      CELLNOOR_TLS_SETTINGS: tls /run/secrets/tls_certificate /run/secrets/tls_key
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    secrets:
      - tls_certificate
      - tls_key
secrets:
  tls_certificate:
    file: ${CELLNOOR_TLS_CERTIFICATE_PATH}
  tls_key:
    file: ${CELLNOOR_TLS_KEY_PATH}
