services:
  cellnoor-api:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-api:latest
    pull_policy: always
    secrets:
      - source: initial_data
        uid: "10001"
  cellnoor-ui:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-ui:latest
    pull_policy: always
    environment:
      PUBLIC_URL: &public_url https://cellnoor.jax.org
  caddy:
    environment:
      PUBLIC_URL: *public_url
      TLS_SETTINGS: /run/secrets/tls_certificate /run/secrets/tls_key
    secrets:
      - tls_certificate
      - tls_key
secrets:
  initial_data:
    file: ${CELLNOOR_INITIAL_DATA_PATH}
  tls_certificate:
    file: ${CELLNOOR_TLS_CERTIFICATE_PATH}
  tls_key:
    file: ${CELLNOOR_TLS_KEY_PATH}
