# TODO: update this with cellnoor-ui
services:
  db:
    ports:
      - "5432:5432"
  cellnoor-auth:
    environment:
      PUBLIC_AUTH_URL: &public_auth_url https://localhost/auth
  cellnoor:
    build:
      args:
        BUILD_PROFILE: dev
    environment:
      PUBLIC_AUTH_URL: *public_auth_url
      PUBLIC_FILES_URL: &public_files_url https://localhost/files
  caddy:
    environment:
      PUBLIC_AUTH_URL: *public_auth_url
      PUBLIC_API_URL: https://localhost/api
      PUBLIC_UI_URL: "TODO"
      PUBLIC_FILES_URL: *public_files_url
