# This is the base compose file. Merge this with one of compose.dev.yaml of compose.prod.yaml to produce a running
# application with the following command:
# docker compose --file compose.yaml --file compose.dev.yaml

# Shared resources
volumes:
  db-data:
  db-socket:
  auth-socket:
  api-socket:
  ui-socket:
  caddy-data:
  caddy-config:
  static-files:
secrets:
  root_db_password:
    environment: CELLNOOR_ROOT_DB_PASSWORD
  app_db_password:
    environment: CELLNOOR_APP_DB_PASSWORD
  auth_db_password:
    environment: CELLNOOR_AUTH_DB_PASSWORD
  auth_secret:
    environment: CELLNOOR_AUTH_SECRET
  microsoft_entra_tenant_id:
    environment: CELLNOOR_MICROSOFT_ENTRA_TENANT_ID
  microsoft_entra_client_id:
    environment: CELLNOOR_MICROSOFT_ENTRA_CLIENT_ID
  microsoft_entra_client_secret:
    environment: CELLNOOR_MICROSOFT_ENTRA_CLIENT_SECRET
services:
  db:
    image: postgres:18-alpine
    restart: always
    secrets: [root_db_password, app_db_password, auth_db_password]
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/root_db_password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    pull_policy: weekly
    healthcheck:
      test: pg_isready || exit 1
      interval: 5m
      start_period: 10s
      start_interval: 0.5s
      timeout: 5s
      retries: 10
    volumes:
      [
        &db_data_volume db-data:/var/lib/postgresql,
        &db_socket_volume db-socket:/run/postgresql,
        ./initial-data.json:/initial-data.json,
      ]
  migrate:
    image: migrate/migrate
    secrets: [root_db_password]
    depends_on:
      db:
        condition: service_healthy
    # We override the entrypoint to pass in the password file
    entrypoint: /bin/sh -c 'migrate -path /migrations -database postgresql://postgres:$(cat /run/secrets/root_db_password)@/?host=/var/run/postgresql up'
    volumes: [./db/migrations:/migrations, *db_socket_volume]
  cellnoor-auth:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: packages/cellnoor-auth
      target: final
    environment:
      DB_NAME: &db_name postgres
      DB_HOST: &db_host /run/postgresql
      UNIX_DOMAIN_SOCKET: &auth_socket /run/cellnoor-auth/cellnoor-auth.sock
    secrets:
      [
        auth_db_password,
        auth_secret,
        microsoft_entra_tenant_id,
        microsoft_entra_client_id,
        microsoft_entra_client_secret,
      ]
    volumes:
      [*db_socket_volume, &auth_socket_volume auth-socket:/run/cellnoor-auth]
  cellnoor:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: crates
      target: final
      args:
        UID: &uid "10001"
        SOCKET: &api_socket /run/cellnoor/cellnoor.sock
        STATIC_FILES_DIR: &static_files_dir /static-files
    environment:
      DB__HOST: *db_host
      # This is hardcoded for simplicity, but it may behoove us to set an explicit dbname in the db service definition
      # and use that here
      DB__DBNAME: postgres
      STATIC_FILES_DIR: *static_files_dir
      LISTEN_ON: *api_socket
    secrets: [auth_secret, app_db_password]
    volumes:
      - *db_socket_volume
      - &api_socket_volume api-socket:/run/cellnoor
      - &static_files_volume static-files:/static-files
    healthcheck:
      test: curl --fail --http2-prior-knowledge --unix-socket /run/cellnoor/cellnoor.sock http://localhost/health || exit 1
      interval: 5m
      start_period: 10s
      start_interval: 0.5s
      timeout: 5s
      retries: 10
  cellnoor-ui:
    build:
      context: packages/cellnoor-ui
      target: final
      args:
        UID: *uid
        SOCKET_PATH: &ui_socket /run/cellnoor-ui/cellnoor-ui.sock
      tags:
        - ghcr.io/thejacksonlaboratory/cellnoor-ui:latest
    environment:
      # https://github.com/oven-sh/bun/issues/14299
      HOST: ""
      # https://svelte.dev/docs/kit/adapter-node#Environment-variables-PORT-HOST-and-SOCKET_PATH
      SOCKET_PATH: *ui_socket
      API_SOCKET: *api_socket
    depends_on:
      cellnoor:
        condition: service_healthy
    healthcheck:
      test: curl --fail --unix-socket /run/cellnoor-ui/cellnoor-ui.sock http://localhost/health || exit 1
      interval: 5m
      start_period: 10s
      start_interval: 0.5s
      timeout: 5s
      retries: 10
    volumes:
      - *api_socket_volume
      - &ui_socket_volume ui-socket:/run/cellnoor-ui
    secrets: [auth_secret]
  caddy:
    image: caddy:2-alpine
    environment:
      AUTH_SOCKET: *auth_socket
      API_SOCKET: *api_socket
      UI_SOCKET: *ui_socket
      STATIC_FILES_DIR: *static_files_dir
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      [
        ./caddy:/etc/caddy,
        caddy-data:/data,
        caddy-config:/config,
        *auth_socket_volume,
        *api_socket_volume,
        *ui_socket_volume,
        *static_files_volume,
      ]
    pull_policy: always
    depends_on:
      cellnoor:
        condition: service_healthy
