services:
  cellnoor-auth:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-auth:latest
    pull_policy: always
    environment:
      PUBLIC_AUTH_URL: &public_auth_url ${CELLNOOR_AUTH_URL}
      REDIRECT_TO: &public_ui_url ${CELLNOOR_UI_URL}
  cellnoor:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor:latest
    pull_policy: always
    environment:
      MAX_DB_POOL_SIZE: "4"
      PUBLIC_AUTH_URL: *public_auth_url
      PUBLIC_FILES_URL: &public_files_url ${CELLNOOR_FILES_URL}
  cellnoor-ui:
    build: !reset null
    image: ghcr.io/thejacksonlaboratory/cellnoor-ui:latest
    pull_policy: always
    environment:
      PUBLIC_AUTH_URL: *public_auth_url
  caddy:
    environment:
      PUBLIC_AUTH_URL: *public_auth_url
      PUBLIC_API_URL: ${CELLNOOR_API_URL}
      PUBLIC_UI_URL: *public_ui_url
      PUBLIC_FILES_URL: *public_files_url
      TLS_SETTINGS: tls /run/secrets/tls_certificate /run/secrets/tls_key
    secrets:
      - tls_certificate
      - tls_key
secrets:
  tls_certificate:
    file: ${CELLNOOR_TLS_CERTIFICATE_PATH}
  tls_key:
    file: ${CELLNOOR_TLS_KEY_PATH}
