services:
  db:
    ports:
      - "5432:5432"
  cellnoor-auth:
    environment:
      NODE_ENV: &node_env development
  cellnoor-api:
    build:
      args:
        BUILD_PROFILE: dev
  cellnoor-ui:
    environment:
      NODE_ENV: *node_env
  caddy:
    environment:
      CELLNOOR_PUBLIC_BASE_URL: cellnoor.localhost
