[package]
edition.workspace = true
name = "ranged"

[dependencies]
deranged.workspace = true
diesel = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }


[lints]
workspace = true

[features]
diesel = ["dep:diesel"]
schemars = ["dep:schemars"]
serde = ["dep:serde", "deranged/serde"]
