[package]
name = "positive"
version = "0.1.0"
edition.workspace = true

[dependencies]
postgres-types = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[lints]
workspace = true

[features]
serde = ["dep:serde"]
schemars = ["dep:schemars"]
postgres-types = ["dep:postgres-types"]
