[package]
edition.workspace = true
name = "nonempty"

[dependencies]
bytes = {workspace = true, optional = true}
postgres-types = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror.workspace = true


[lints]
workspace = true

[features]
schemars = ["dep:schemars", "serde"]
serde = ["dep:serde"]
postgres-types = ["dep:postgres-types", "dep:bytes"]


[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true
