[package]
edition.workspace = true
name = "cellnoor-models"
version = "0.1.0"

[dependencies]
bon = { workspace = true, optional = true }
cellnoor-schema = { path = "../cellnoor-schema", optional = true }
csv.workspace = true
default-vec = { path = "../default-vec", features = ["serde"] }
diesel = { workspace = true, optional = true, features = [
  "32-column-tables",
  "serde_json",
  "uuid",
  "without-deprecated",
] }
diesel-derive-newtype.workspace = true
jiff.workspace = true
jiff-diesel = { workspace = true, optional = true }
macro-attributes = { path = "macro-attributes" }
macros = { path = "macros" }
non-empty = { path = "../non-empty", features = ["serde"] }
ranged = { version = "0.1.0", path = "../ranged", features = ["serde"] }
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true

[lints]
workspace = true

[features]
app = [
  "default-vec/schemars",
  "dep:cellnoor-schema",
  "dep:diesel",
  "dep:jiff-diesel",
  "dep:schemars",
  "non-empty/diesel",
  "non-empty/schemars",
  "ranged/diesel",
  "ranged/schemars",
]
builder = ["dep:bon"]
