// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseError } from "./DatabaseError";

export type AuthError = { "type": "no_auth_token_found", "info": { message: string, } } | { "type": "invalid_auth_token", "info": { message: string, } } | { "type": "database", "info": DatabaseError };
