// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockFixative } from "./BlockFixative";
import type { NonEmptyString } from "./NonEmptyString";
import type { Species } from "./Species";
import type { JsonValue } from "./serde_json/JsonValue";

export type BlockCreation = { "embedded_in": "optimal_cutting_temperature_compound", fixative?: BlockFixative, readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, } | { "embedded_in": "carboxymethyl_cellulose", fixative?: BlockFixative, readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, } | { "embedded_in": "paraffin", fixative: BlockFixative, readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, };
