// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { NonEmptyVec } from "./NonEmptyVec";
import type { RangedU32 } from "./RangedU32";
import type { JsonValue } from "./serde_json/JsonValue";

export type CellSuspensionCreation = { created_at?: string, target_cell_recovery?: RangedU32, preparer_ids: NonEmptyVec<string>, readable_id: NonEmptyString, parent_specimen_id: string, additional_data?: JsonValue, };
