// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";

export type PersonCreation = { email: NonEmptyString, name: NonEmptyString, orcid?: NonEmptyString, institution_id: string, microsoft_entra_oid?: string, };
