// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockCreation } from "./BlockCreation";
import type { SuspensionSpecimenCreation } from "./SuspensionSpecimenCreation";
import type { TissueCreation } from "./TissueCreation";

export type SpecimenCreation = { "type": "block" } & BlockCreation | { "type": "suspension" } & SuspensionSpecimenCreation | { "type": "tissue" } & TissueCreation;
