// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryopreservedSuspensionCreation } from "./CryopreservedSuspensionCreation";
import type { CryopreservedTissueCreation } from "./CryopreservedTissueCreation";
import type { FixedBlockCreation } from "./FixedBlockCreation";
import type { FlashFrozenBlockCreation } from "./FlashFrozenBlockCreation";
import type { NonCryopreservedSuspensionCreation } from "./NonCryopreservedSuspensionCreation";
import type { NonCryopreservedTissueCreation } from "./NonCryopreservedTissueCreation";

export type SpecimenCreation = { "type": "fixed_block" } & FixedBlockCreation | { "type": "flash_frozen_block" } & FlashFrozenBlockCreation | { "type": "cryopreserved_suspension" } & CryopreservedSuspensionCreation | { "type": "non_cryopreserved_suspsension" } & NonCryopreservedSuspensionCreation | { "type": "cryopreserved_tissue" } & CryopreservedTissueCreation | { "type": "non_cryopreserved_tissue" } & NonCryopreservedTissueCreation;
