// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockEmbeddingMatrix } from "./BlockEmbeddingMatrix";
import type { Fixative } from "./Fixative";
import type { Species } from "./Species";
import type { SpecimenType } from "./SpecimenType";
import type { ThermalPreservationMethod } from "./ThermalPreservationMethod";
import type { JsonValue } from "./serde_json/JsonValue";

export type SpecimenFilter = { ids?: Array<string>, names?: Array<string>, submitted_by?: Array<string>, labs?: Array<string>, received_before?: string, received_after?: string, species?: Array<Species>, host_species?: Array<Species>, types?: Array<SpecimenType>, embedded_in?: Array<BlockEmbeddingMatrix>, fixatives?: Array<Fixative>, thermal_preservation_methods?: Array<ThermalPreservationMethod>, fresh?: boolean, tissues?: Array<string>, returned_before?: string, returned_after?: string, returned_by?: Array<string>, additional_data?: JsonValue, };
