// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { Species } from "./Species";
import type { SuspensionFixative } from "./SuspensionFixative";
import type { ThermalPreservationMethod } from "./ThermalPreservationMethod";
import type { JsonValue } from "./serde_json/JsonValue";

export type SuspensionSpecimenCreation = { "preservation_state": "fixed", fixative: SuspensionFixative, readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, } | { "preservation_state": "fresh", readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, } | { "preservation_state": "thermally_preserved", thermal_preservation_method: ThermalPreservationMethod, readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, };
