// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuspensionContent } from "./SuspensionContent";

export type SuspensionMeasurementValidationError = { "type": "wrong_suspension_content", "info": { expected_suspension_content: SuspensionContent, } };
