# This is the base compose file. Merge this with one of compose.dev.yaml of compose.prod.yaml to produce a running
# application with the following command:
# docker compose --file compose.yaml --file compose.dev.yaml
services:
  &db_host db:
    image: postgres:18-alpine
    restart: always
    user: &db_root_user postgres
    secrets: ["db_root_password"]
    environment:
      POSTGRES_USER: *db_root_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      POSTGRES_DB: &db_name cellnoor
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    pull_policy: always
    healthcheck:
      test: pg_isready --dbname cellnoor || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    volumes: ["db-data:/var/lib/postgresql", "db-socket:/var/run/postgresql"]
  migrate:
    image: migrate/migrate
    secrets: ["db_root_password"]
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "migrate -path /migrations -database 'postgres://postgres:'$(cat /run/secrets/db_root_password)'@db/cellnoor?sslmode=disable' up",
      ]
    volumes: ["./db/migrations:/migrations"]
volumes:
  db-data:
  db-socket:
secrets:
  db_root_password:
    environment: CELLNOOR_DB_ROOT_PASSWORD
  # cellnoor_api_db_password:
  #   environment: CELLNOOR_API_DB_PASSWORD
  # cellnoor_ui_db_password:
  #   environment: CELLNOOR_UI_DB_PASSWORD
  # microsoft_entra_client_id:
  #   environment: CELLNOOR_MICROSOFT_ENTRA_CLIENT_ID
  # microsoft_entra_client_secret:
  #   environment: CELLNOOR_MICROSOFT_ENTRA_CLIENT_SECRET
  # microsoft_entra_tenant:
  #   environment: CELLNOOR_MICROSOFT_ENTRA_TENANT
  # auth_secret:
  #   environment: CELLNOOR_AUTH_SECRET
