[package]
name = "cellnoor-api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "openapi"

[dependencies]
csv.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tower-http.workspace = true
camino.workspace = true
rand.workspace = true
aide.workspace = true
csvranger.workspace = true
jsonwebtoken.workspace = true
bytes.workspace = true
serde.workspace = true
deadpool-postgres.workspace = true
cellnoor-types = { path = "../cellnoor-types", features = [
    "schemars",
    "postgres-types",
] }
axum.workspace = true
axum-extra.workspace = true
anyhow.workspace = true
uuid.workspace = true
schemars.workspace = true
secrecy.workspace = true
postgres-types.workspace = true
jiff.workspace = true
dotenvy.workspace = true
thiserror.workspace = true
config.workspace = true
tokio.workspace = true
strum.workspace = true
sha3.workspace = true
regex.workspace = true
futures.workspace = true
serde_json.workspace = true
zstd.workspace = true
indexmap.workspace = true

[dev-dependencies]
uuid = { workspace = true, features = ["v4"] }
pretty_assertions.workspace = true
