[package]
name = "cellnoor-types"
version = "0.1.0"
edition.workspace = true

[dependencies]
nonempty = {path = "../nonempty"}
jiff.workspace = true
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
uuid.workspace = true
postgres-types = { workspace = true, optional = true }

[lints]
workspace = true

[features]
serde = ["dep:serde", "nonempty/serde"]
schemars = ["dep:schemars", "nonempty/schemars"]
postgres-types = ["dep:postgres-types", "nonempty/postgres-types"]
