/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description plain text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": unknown;
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Institution"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewInstitution"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Institution"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/institutions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Institution"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/institutions/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonSummary"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonSummary"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewPerson"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatePersonError"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PersonUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatePersonError"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/people/{id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpecimenSummary"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}/chromium-datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description no content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewProject"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonSummary"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description no content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description no content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/projects/{id}/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpecimenSummary"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/chromium-datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description no content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpecimenSummary"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewSpecimen"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Specimen"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specimens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Specimen"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specimens/{id}/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpecimenMeasurement"][];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpecimenMeasurementFields"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpecimenMeasurement"];
                    };
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specimens/{id}/chromium-datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description no content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: components["schemas"]["AuthError"] | components["schemas"]["DatabaseError"];
        AuthError: ({
            /** @constant */
            type: "database";
        } & components["schemas"]["DatabaseError"]) | {
            message: string;
            /** @constant */
            type: "invalid_auth_token";
        } | {
            message: string;
            /** @constant */
            type: "no_auth_token_found";
        } | {
            message: string;
            /** @constant */
            type: "other";
        } | {
            /** @constant */
            type: "permission_denied";
        };
        /** @enum {string} */
        BlockEmbeddingMatrix: "carboxymethyl_cellulose" | "optimal_cutting_temperature_compound" | "paraffin";
        /** @enum {string} */
        BlockFixative: "formaldehyde_derivative";
        CreatePersonError: ({
            /** @constant */
            type: "database";
        } & components["schemas"]["DatabaseError"]) | {
            /** @constant */
            type: "invalid_email";
        };
        DatabaseError: {
            message: string;
            /** @constant */
            type: "data";
        } | {
            fields: string[];
            resource: string;
            /** @constant */
            type: "duplicate_resource";
            values: string[];
        } | {
            referenced_resource: string;
            resource: string;
            /** @constant */
            type: "invalid_reference";
            value?: string | null;
        } | {
            /** @constant */
            type: "resource_not_found";
        } | {
            message: string;
            /** @constant */
            type: "other";
        };
        /** @enum {string} */
        Fixative: "dithiobis_succinimidylpropionate" | "formaldehyde_derivative";
        Institution: {
            /** Format: uuid */
            id: string;
            links: components["schemas"]["Links"];
            name: string;
        };
        InstitutionFilter: {
            /** @default null */
            ids: string[] | null;
            /** @default null */
            names: string[] | null;
        };
        InstitutionOrderBy: {
            descending?: boolean | null;
            /** @constant */
            field: "id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "name";
        };
        Link: string | string[];
        Links: {
            [key: string]: components["schemas"]["Link"];
        };
        NewBlock: {
            additional_data?: unknown;
            /** @constant */
            embedded_in: "optimal_cutting_temperature_compound";
            fixative?: components["schemas"]["BlockFixative"] | null;
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        } | {
            additional_data?: unknown;
            /** @constant */
            embedded_in: "carboxymethyl_cellulose";
            fixative?: components["schemas"]["BlockFixative"] | null;
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        } | {
            additional_data?: unknown;
            /** @constant */
            embedded_in: "paraffin";
            fixative: components["schemas"]["BlockFixative"];
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        };
        NewInstitution: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        NewPerson: {
            email: string;
            /** Format: uuid */
            institution_id: string;
            /** Format: uuid */
            microsoft_entra_oid?: string | null;
            name: string;
            orcid?: string | null;
        };
        NewProject: {
            /** Format: date-time */
            ended_at: string;
            name: string;
            /** Format: date-time */
            started_at: string;
        };
        NewSpecimen: ({
            /** @constant */
            type: "block";
        } & components["schemas"]["NewBlock"]) | ({
            /** @constant */
            type: "suspension";
        } & components["schemas"]["NewSuspensionSpecimen"]) | ({
            /** @constant */
            type: "tissue";
        } & components["schemas"]["NewTissue"]);
        NewSuspensionSpecimen: {
            additional_data?: unknown;
            fixative: components["schemas"]["Fixative"];
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** @constant */
            preservation_state: "fixed";
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        } | {
            additional_data?: unknown;
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** @constant */
            preservation_state: "fresh";
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        } | {
            additional_data?: unknown;
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** @constant */
            preservation_state: "thermally_preserved";
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            thermal_preservation_method: components["schemas"]["SuspensionThermalPreservation"];
            tissue: string;
        };
        NewTissue: {
            additional_data?: unknown;
            fixative: components["schemas"]["Fixative"];
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** @constant */
            preservation_state: "fixed";
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        } | {
            additional_data?: unknown;
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** @constant */
            preservation_state: "fresh";
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            tissue: string;
        } | {
            additional_data?: unknown;
            host_species?: components["schemas"]["Species"] | null;
            name: string;
            /** @constant */
            preservation_state: "thermally_preserved";
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            thermal_preservation_method: components["schemas"]["ThermalPreservationMethod"];
            tissue: string;
        };
        Person: {
            email?: string | null;
            email_verified: boolean;
            /** Format: uuid */
            id: string;
            institution: components["schemas"]["Institution"];
            /** Format: uuid */
            institution_id: string;
            links: components["schemas"]["Links"];
            /** Format: uuid */
            microsoft_entra_oid?: string | null;
            name: string;
            orcid?: string | null;
        };
        PersonFilter: {
            /** @default null */
            emails: string[] | null;
            /** @default null */
            ids: string[] | null;
            /** @default null */
            institution_ids: string[] | null;
            /** @default null */
            microsoft_entra_oids: string[] | null;
            /** @default null */
            names: string[] | null;
            /** @default null */
            orcids: string[] | null;
        };
        PersonOrderBy: {
            descending?: boolean | null;
            /** @constant */
            field: "id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "name";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "email";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "email_verified";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "institution_id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "orcid";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "microsoft_entra_oid";
        };
        PersonSummary: {
            email?: string | null;
            email_verified: boolean;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            institution_id: string;
            links: components["schemas"]["Links"];
            /** Format: uuid */
            microsoft_entra_oid?: string | null;
            name: string;
            orcid?: string | null;
        };
        PersonUpdate: {
            /** @default null */
            email: string | null;
            /**
             * Format: uuid
             * @default null
             */
            institution_id: string | null;
            /** @default null */
            is_admin: boolean | null;
            /** @default null */
            is_biology_staff: boolean | null;
            /** @default null */
            is_computational_staff: boolean | null;
            /**
             * Format: uuid
             * @default null
             */
            microsoft_entra_oid: string | null;
            /** @default null */
            name: string | null;
            /** @default null */
            orcid: string | null;
        };
        Project: {
            /** Format: date-time */
            ended_at: string;
            /** Format: uuid */
            id: string;
            links: components["schemas"]["Links"];
            name: string;
            /** Format: date-time */
            started_at: string;
        };
        ProjectFilter: {
            /**
             * Format: date-time
             * @default null
             */
            ended_after: string | null;
            /**
             * Format: date-time
             * @default null
             */
            ended_before: string | null;
            /** @default null */
            ids: string[] | null;
            /** @default null */
            names: string[] | null;
            /**
             * Format: date-time
             * @default null
             */
            started_after: string | null;
            /**
             * Format: date-time
             * @default null
             */
            started_before: string | null;
        };
        ProjectOrderBy: {
            descending?: boolean | null;
            /** @constant */
            field: "id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "name";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "started_at";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "ended_at";
        };
        /** @enum {string} */
        Species: "ambystoma_mexicanum" | "canis_familiaris" | "callithrix_jacchus" | "drosophila_melanogaster" | "gasterosteus_aculeatus" | "homo_sapiens" | "mus_musculus" | "rattus_norvegicus" | "sminthopsis_crassicaudata";
        Specimen: {
            additional_data?: unknown;
            embedded_in?: components["schemas"]["BlockEmbeddingMatrix"] | null;
            fixative?: components["schemas"]["Fixative"] | null;
            host_species?: components["schemas"]["Species"] | null;
            /** Format: uuid */
            id: string;
            links: components["schemas"]["Links"];
            name: string;
            project: components["schemas"]["Project"];
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            submitted_by: components["schemas"]["PersonSummary"];
            thermal_preservation_method?: components["schemas"]["ThermalPreservationMethod"] | null;
            tissue: string;
            type_: components["schemas"]["SpecimenType"];
        };
        SpecimenFilter: {
            /** @default null */
            additional_data: unknown;
            /** @default null */
            embedded_in: components["schemas"]["BlockEmbeddingMatrix"][] | null;
            /** @default null */
            fixatives: components["schemas"]["Fixative"][] | null;
            /** @default null */
            fresh: boolean | null;
            /** @default null */
            host_species: components["schemas"]["Species"][] | null;
            /** @default null */
            ids: string[] | null;
            /** @default null */
            names: string[] | null;
            /** @default null */
            projects: string[] | null;
            /**
             * Format: date-time
             * @default null
             */
            received_after: string | null;
            /**
             * Format: date-time
             * @default null
             */
            received_before: string | null;
            /**
             * Format: date-time
             * @default null
             */
            returned_after: string | null;
            /**
             * Format: date-time
             * @default null
             */
            returned_before: string | null;
            /** @default null */
            returned_by: string[] | null;
            /** @default null */
            species: components["schemas"]["Species"][] | null;
            /** @default null */
            submitted_by: string[] | null;
            /** @default null */
            thermal_preservation_methods: components["schemas"]["ThermalPreservationMethod"][] | null;
            /** @default null */
            tissues: string[] | null;
            /** @default null */
            types: components["schemas"]["SpecimenType"][] | null;
        };
        SpecimenMeasurement: {
            data: components["schemas"]["SpecimenMeasurementData"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            measured_at: string;
            /** Format: uuid */
            measured_by: string;
            /** Format: uuid */
            specimen_id: string;
        };
        SpecimenMeasurementData: {
            instrument_name?: string | null;
            /** @constant */
            quantity: "DV200";
            /** Format: uint32 */
            value: number;
        } | {
            instrument_name?: string | null;
            /** @constant */
            quantity: "RIN";
            /** Format: uint32 */
            value: number;
        };
        SpecimenMeasurementFields: {
            data: components["schemas"]["SpecimenMeasurementData"];
            /** Format: date-time */
            measured_at: string;
            /** Format: uuid */
            measured_by: string;
        };
        SpecimenOrderBy: {
            descending?: boolean | null;
            /** @constant */
            field: "id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "readable_id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "name";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "submitted_by";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "project_id";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "received_at";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "species";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "host_species";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "returned_at";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "returned_by";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "type_";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "embedded_in";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "fixative";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "thermal_preservation_method";
        } | {
            descending?: boolean | null;
            /** @constant */
            field: "tissue";
        };
        SpecimenSummary: {
            additional_data?: unknown;
            embedded_in?: components["schemas"]["BlockEmbeddingMatrix"] | null;
            fixative?: components["schemas"]["Fixative"] | null;
            host_species?: components["schemas"]["Species"] | null;
            /** Format: uuid */
            id: string;
            links: components["schemas"]["Links"];
            name: string;
            /** Format: uuid */
            project_id: string;
            readable_id: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            returned_by?: string | null;
            species: components["schemas"]["Species"];
            /** Format: uuid */
            submitted_by: string;
            thermal_preservation_method?: components["schemas"]["ThermalPreservationMethod"] | null;
            tissue: string;
            type_: components["schemas"]["SpecimenType"];
        };
        /** @enum {string} */
        SpecimenType: "block" | "suspension" | "tissue";
        /** @enum {string} */
        SuspensionThermalPreservation: "controlled_rate_freezing";
        /** @enum {string} */
        ThermalPreservationMethod: "controlled_rate_freezing" | "flash_freezing";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ApiError = components['schemas']['ApiError'];
export type AuthError = components['schemas']['AuthError'];
export type BlockEmbeddingMatrix = components['schemas']['BlockEmbeddingMatrix'];
export type BlockFixative = components['schemas']['BlockFixative'];
export type CreatePersonError = components['schemas']['CreatePersonError'];
export type DatabaseError = components['schemas']['DatabaseError'];
export type Fixative = components['schemas']['Fixative'];
export type Institution = components['schemas']['Institution'];
export type InstitutionFilter = components['schemas']['InstitutionFilter'];
export type InstitutionOrderBy = components['schemas']['InstitutionOrderBy'];
export type Link = components['schemas']['Link'];
export type Links = components['schemas']['Links'];
export type NewBlock = components['schemas']['NewBlock'];
export type NewInstitution = components['schemas']['NewInstitution'];
export type NewPerson = components['schemas']['NewPerson'];
export type NewProject = components['schemas']['NewProject'];
export type NewSpecimen = components['schemas']['NewSpecimen'];
export type NewSuspensionSpecimen = components['schemas']['NewSuspensionSpecimen'];
export type NewTissue = components['schemas']['NewTissue'];
export type Person = components['schemas']['Person'];
export type PersonFilter = components['schemas']['PersonFilter'];
export type PersonOrderBy = components['schemas']['PersonOrderBy'];
export type PersonSummary = components['schemas']['PersonSummary'];
export type PersonUpdate = components['schemas']['PersonUpdate'];
export type Project = components['schemas']['Project'];
export type ProjectFilter = components['schemas']['ProjectFilter'];
export type ProjectOrderBy = components['schemas']['ProjectOrderBy'];
export type Species = components['schemas']['Species'];
export type Specimen = components['schemas']['Specimen'];
export type SpecimenFilter = components['schemas']['SpecimenFilter'];
export type SpecimenMeasurement = components['schemas']['SpecimenMeasurement'];
export type SpecimenMeasurementData = components['schemas']['SpecimenMeasurementData'];
export type SpecimenMeasurementFields = components['schemas']['SpecimenMeasurementFields'];
export type SpecimenOrderBy = components['schemas']['SpecimenOrderBy'];
export type SpecimenSummary = components['schemas']['SpecimenSummary'];
export type SpecimenType = components['schemas']['SpecimenType'];
export type SuspensionThermalPreservation = components['schemas']['SuspensionThermalPreservation'];
export type ThermalPreservationMethod = components['schemas']['ThermalPreservationMethod'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
