[package]
edition.workspace = true
name = "scamplers-typescript"
version = "0.1.0"

[dependencies]
clap.workspace = true
heck.workspace = true
scamplers-models = { version = "0.1.0", path = "../scamplers-models", features = [
  "typescript",
] }
serde_json.workspace = true
ts-rs.workspace = true

[lints]
workspace = true
