// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbError } from "./DbError";

export type AuthError = { "type": "unauthorized", "info": { message: string, } } | { "type": "database", "info": DbError };
