// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";
import type { PositiveU32 } from "./PositiveU32";

export type CdnaValidationError = { "type": "non_existent_assay_library_type", "info": { assay_id: string, } } | { "type": "volume", "info": { assay_id: string, library_type: LibraryType, expected: PositiveU32, found: PositiveU32, } };
