// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";

export type CdnaValidationError = { "type": "volume", "info": { assay_id: string, library_type: LibraryType, expected: number, found: number, } };
