// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CdnaQuery = { filter?: { ids?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "field": "id", descending?: boolean, } | { "field": "readable_id", descending?: boolean, } | { "field": "library_type", descending?: boolean, } | { "field": "prepared_at", descending?: boolean, } | { "field": "gem_pool_id", descending?: boolean, } | { "field": "n_amplification_cycles", descending?: boolean, }>, };
