// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuspensionMeasurementFields } from "./SuspensionMeasurementFields";

export type CellSuspensionMeasurementCreation = SuspensionMeasurementFields;
