// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChromiumDatasetValidationError = { "type": "different_gem_pools" } | { "type": "cmdline", "info": { expected: Array<string>, } } | { "type": "data_path" } | { "type": "libraries_not_sequenced", "info": { library_ids: Array<string>, } };
