// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitialDataValidationError } from "./InitialDataValidationError";
import type { LabValidationError } from "./LabValidationError";
import type { PersonValidationError } from "./PersonValidationError";
import type { SpecimenMeasurementValidationError } from "./SpecimenMeasurementValidationError";
import type { SpecimenValidationError } from "./SpecimenValidationError";

export type DataValidationError = { "type": "insert_initial_data", "info": InitialDataValidationError } | { "type": "create_person", "info": PersonValidationError } | { "type": "create_lab", "info": LabValidationError } | { "type": "create_specimen", "info": SpecimenValidationError } | { "type": "create_specimen_measurement", "info": SpecimenMeasurementValidationError } | { "type": "create_suspension_measurement", "info": SpecimenMeasurementValidationError } | { "type": "create_suspension_pool_measurement", "info": SpecimenMeasurementValidationError };
