// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstitutionOrdinalColumns } from "./InstitutionOrdinalColumns";

export type InstitutionQuery = { limit?: bigint, offset?: bigint, order_by?: Array<{ field: InstitutionOrdinalColumns, descending?: boolean, }>, ids: Array<string> | null, names: Array<string> | null, };
