// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonSummary } from "./PersonSummary";

export type Lab = { pi: PersonSummary, id: string, links: { [key in string]?: string }, name: string, pi_id: string, delivery_dir: string, };
