// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabQuery = { filter?: { ids?: Array<string>, names?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "field": "id", descending?: boolean, } | { "field": "name", descending?: boolean, } | { "field": "delivery_dir", descending?: boolean, } | { "field": "pi_id", descending?: boolean, }>, };
