// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabOrdinalColumns } from "./LabOrdinalColumns";

export type LabQuery = { limit?: bigint, offset?: bigint, order_by?: Array<{ field: LabOrdinalColumns, descending?: boolean, }>, ids: Array<string> | null, names: Array<string> | null, };
