// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedMetricsFile } from "./ParsedMetricsFile";
import type { Row } from "./Row";
import type { JsonValue } from "./serde_json/JsonValue";

export type ParsedMetrics = { "format": "json", files: Array<ParsedMetricsFile<{ [key in string]?: JsonValue }>>, } | { "format": "single_row_csv", files: Array<ParsedMetricsFile<{ [key in string]?: number }>>, } | { "format": "multi_row_csv", files: Array<ParsedMetricsFile<Array<Row>>>, };
