// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";

export type ParsedMetricsFile<D> = { parsed_data: D, filename: NonEmptyString, raw_contents: string, };
