// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Institution } from "./Institution";
import type { UserRole } from "./UserRole";

export type Person = { roles: Array<UserRole>, institution: Institution, id: string, email: string | null, email_verified: boolean, links: { [key in string]?: string }, name: string, orcid: string | null, institution_id: string, microsoft_entra_oid: string | null, };
