// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonOrdinalColumns } from "./PersonOrdinalColumns";

export type PersonQuery = { limit?: bigint, offset?: bigint, order_by?: Array<{ field: PersonOrdinalColumns, descending?: boolean, }>, ids: Array<string> | null, name: string | null, email: string | null, orcid: string | null, microsoft_entra_oids: Array<string> | null, };
