// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonSummary = { id: string, email?: string, email_verified: boolean, links: { [key in string]?: string }, name: string, orcid?: string, institution_id: string, microsoft_entra_oid?: string, };
