// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonQuery = { filter?: { ids?: Array<string>, names?: Array<string>, emails?: Array<string>, institution_ids?: Array<string>, orcids?: Array<string>, microsoft_entra_oids?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "field": "email", descending: boolean, } | { "field": "id", descending: boolean, } | { "field": "name", descending: boolean, }>, };
