// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";
import type { JsonValue } from "./serde_json/JsonValue";

export type Row = { metric_value: JsonValue, category: string, library_type: LibraryType, grouped_by: string, group_name: string, metric_name: string, };
