// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvalidMeasurement } from "./InvalidMeasurement";

export type SpecimenMeasurementValidationError = { "type": "invalid_viability", "info": InvalidMeasurement };
