// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingMatrix } from "./EmbeddingMatrix";
import type { Fixative } from "./Fixative";
import type { Species } from "./Species";
import type { SpecimenType } from "./SpecimenType";
import type { JsonValue } from "./serde_json/JsonValue";

export type SpecimenQuery = { filter?: { ids?: Array<string>, names?: Array<string>, submitted_by?: Array<string>, labs?: Array<string>, received_before: Date, received_after: Date, species?: Array<Species>, host_species?: Array<Species>, types?: Array<SpecimenType>, embedded_in?: Array<EmbeddingMatrix>, fixatives?: Array<Fixative>, frozen?: boolean, cryopreserved?: boolean, tissues?: Array<string>, returned_before: Date, returned_after: Date, returned_by?: Array<string>, additional_data?: Array<JsonValue>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "field": "id", descending: boolean, } | { "field": "name", descending: boolean, } | { "field": "readable_id", descending: boolean, } | { "field": "received_at", descending: boolean, } | { "field": "species", descending: boolean, } | { "field": "host_species", descending: boolean, } | { "field": "returned_at", descending: boolean, } | { "field": "type_", descending: boolean, } | { "field": "embedded_in", descending: boolean, } | { "field": "fixative", descending: boolean, } | { "field": "tissue", descending: boolean, }>, };
