// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositiveF32 } from "./PositiveF32";

export type SpecimenMeasurementValidationError = { "type": "invalid_rin", "info": { min: number, max: number, found: PositiveF32, } } | { "type": "invalid_dv200", "info": { min: number, max: number, found: PositiveF32, } };
