// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { PositiveF32 } from "./PositiveF32";
import type { PositiveU32 } from "./PositiveU32";
import type { SuspensionContent } from "./SuspensionContent";
import type { JsonValue } from "./serde_json/JsonValue";

export type SuspensionSummary = { id: string, content: SuspensionContent, links: Links, readable_id: NonEmptyString, parent_specimen_id: string, target_cell_recovery: PositiveU32, created_at?: string, lysis_duration_minutes?: PositiveF32, additional_data?: JsonValue, };
