// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuspensionQuery = { filter?: { ids?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "field": "id", descending?: boolean, } | { "field": "readable_id", descending?: boolean, } | { "field": "parent_specimen_id", descending?: boolean, } | { "field": "created_at", descending?: boolean, } | { "field": "lysis_duration_minutes", descending?: boolean, } | { "field": "target_cell_recovery", descending?: boolean, }>, };
