// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuspensionPoolQuery = { filter?: Record<string, never>, limit?: bigint, offset?: bigint, order_by?: Array<{ "field": "id", descending?: boolean, } | { "field": "readable_id", descending?: boolean, } | { "field": "name", descending?: boolean, } | { "field": "pooled_at", descending?: boolean, }>, };
