// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { NonEmptyVec } from "./NonEmptyVec";
import type { PositiveF32 } from "./PositiveF32";
import type { PositiveU32 } from "./PositiveU32";
import type { JsonValue } from "./serde_json/JsonValue";

export type SuspensionCreationInner = { preparer_ids: NonEmptyVec<string>, tag_ids?: Array<string>, readable_id: NonEmptyString, parent_specimen_id: string, target_cell_recovery: PositiveU32, created_at?: string, lysis_duration_minutes?: PositiveF32, additional_data?: JsonValue, };
