// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountingMethod } from "./CountingMethod";
import type { Micrometer } from "./Micrometer";
import type { Milliliter } from "./Milliliter";
import type { PositiveF32 } from "./PositiveF32";
import type { SuspensionContent } from "./SuspensionContent";
import type { Viability } from "./Viability";
import type { Volume } from "./Volume";

export type SuspensionMeasurementData = { "quantity": "concentration", numerator_unit: SuspensionContent, counting_method?: CountingMethod, post_hybridization: boolean, value: PositiveF32, denominator_unit: Milliliter, } | { "quantity": "viability" } & Viability | { "quantity": "volume" } & Volume | { "quantity": "mean_diameter", object: SuspensionContent, post_hybridization: boolean, value: PositiveF32, unit: Micrometer, };
