// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Microliter } from "./Microliter";
import type { PositiveF32 } from "./PositiveF32";

export type Volume = { post_hybridization: boolean, value: PositiveF32, unit: Microliter, };
