name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build_cellnoor-api
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(cargo metadata --format-version 1 | jq --raw-output '.packages[] | select(.name == "cellnoor-api").version')
          docker push ghcr.io/demhadais/cellnoor-api:${VERSION}
