name: Check OpenAPI document
on:
  push:
    paths:
      - "**/*.rs"

jobs:
  check_openapi_document:
    runs-on: ubuntu-latest
    env:
      CELLNOOR_GENERATE_SCHEMA: false

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Regenerate OpenAPI document
        run: cargo run --bin openapi > regenerated-openapi.json

      - name: Compare committed OpenAPI document to regenerated OpenAPI document
        run: diff openapi.json regenerated-openapi.json
