name: Check OpenAPI document
on:
  push:
    paths:
      - "**/*.rs"

jobs:
  check_openapi_document:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Regenerate OpenAPI document and TypeScript definitions
        run: ./scripts/dev/openapi.sh

      - name: Compare committed files to regenerated files
        run: git diff --exit-code
