name: Check Rust Code
on:
  push:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true
          cache-on-failure: true

      - name: Lint
        working-directory: crates
        run: cargo clippy --workspace --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true
          cache-on-failure: true

      - name: Install nightly toolchain
        run: rustup component add --toolchain nightly-2026-06-13 rustfmt # This is updated weekly-ish

      - name: Format
        working-directory: crates
        run: cargo +nightly-2026-06-13 fmt -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Copy initial data
        run: cp initial-data.sample.json initial-data.json

      - name: Test
        env:
          CELLNOOR_ROOT_DB_PASSWORD: p
          CELLNOOR_APP_DB_PASSWORD: p
          CELLNOOR_AUTH_DB_PASSWORD: p
          CELLNOOR_AUTH_SECRET: ""
          CELLNOOR_MICROSOFT_ENTRA_TENANT_ID: ""
          CELLNOOR_MICROSOFT_ENTRA_CLIENT_ID: ""
          CELLNOOR_MICROSOFT_ENTRA_CLIENT_SECRET: ""
        run: ./scripts/dev/test.sh
