name: Check scamplers-types
on:
  push:
    paths:
      - "**/*.rs"

jobs:
  check_scamplers-types:
    runs-on: ubuntu-latest
    env:
      SCAMPLERS_GENERATE_SCHEMA: false

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Rerun scamplers-typescript
        run: cargo run --package scamplers-typescript -- --output-dir regenerated-typescript-type-definitions

      - name: Compare committed scamplers-types to regenerated scamplers-types
        run: diff --exclude package.json --recursive scamplers-types regenerated-typescript-type-definitions
