name: Check SQL Code
on:
  push:
    paths:
      - "**/*.sql"
jobs:
  lint_sql:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Lint code
        run: sqlfluff lint .
