name: Check TypeScript Code
on:
  push:
    paths:
      - cellnoor-ui/**

jobs:
  lint-format-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: cellnoor-ui
        run: bun install

      - name: Check svelte code
        working-directory: cellnoor-ui
        run: bun run --bun check

      - name: Lint and format
        working-directory: cellnoor-ui
        run: bun run --bun lint

      - name: Test
        working-directory: cellnoor-ui
        run: bun test
