name: Check TypeScript Code
on:
  pull_request:
    branches: ["main"]
    paths:
      - packages/**

jobs:
  lint-format-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: packages/cellnoor-ui
        run: bun install

      - name: Check TypeScript code
        working-directory: packages/cellnoor-ui
        run: bun run --bun check
